In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("ready.")

numpy: 2.4.4
pandas: 2.3.3
ready.


In [2]:
arr = np.array([1, 2, 3, 4, 5])
print("array:", arr)
print("shape:", arr.shape)
print("dtype:", arr.dtype)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nmatrix:\n", matrix)
print("matrix shape:", matrix.shape)

zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
rand = np.random.rand(3, 3)
print("\nzeros:\n", zeros)
print("\nrand:\n", rand)

array: [1 2 3 4 5]
shape: (5,)
dtype: int64

matrix:
 [[1 2 3]
 [4 5 6]]
matrix shape: (2, 3)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

rand:
 [[0.47986788 0.36913983 0.08719685]
 [0.73817155 0.43883319 0.85018462]
 [0.83796726 0.37375886 0.77542807]]


In [3]:
prices = np.array([100, 200, 300, 400])
discount = 0.9
discounted = prices * discount
print("discounted prices:", discounted)

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("a + b:", a + b)

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([10, 20, 30])
print("\nmatrix + row_vector:\n", matrix + row_vector)

discounted prices: [ 90. 180. 270. 360.]
a + b: [11 22 33]

matrix + row_vector:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [4]:
data = np.array([[10, 200, 3000],
                  [20, 250, 3200],
                  [15, 180, 2900],
                  [25, 220, 3100]])

col_mean = data.mean(axis=0)
col_std = data.std(axis=0)

print("column means:", col_mean)
print("column stds:", col_std)

normalized = (data - col_mean) / col_std
print("\nnormalized data:\n", normalized)

column means: [  17.5  212.5 3050. ]
column stds: [  5.59016994  25.86020108 111.80339887]

normalized data:
 [[-1.34164079 -0.48336824 -0.4472136 ]
 [ 0.4472136   1.45010473  1.34164079]
 [-0.4472136  -1.25675744 -1.34164079]
 [ 1.34164079  0.29002095  0.4472136 ]]


In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("first 3:", arr[:3])
print("last 2:", arr[-2:])
print("every other:", arr[::2])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nfirst row:", matrix[0])
print("first column:", matrix[:, 0])
print("element row1,col2:", matrix[1, 2])

ages = np.array([22, 35, 58, 19, 41, 67, 28])
mask = ages > 30
print("\nmask:", mask)
print("ages over 30:", ages[mask])

first 3: [10 20 30]
last 2: [50 60]
every other: [10 30 50]

first row: [1 2 3]
first column: [1 4 7]
element row1,col2: 6

mask: [False  True  True False  True  True False]
ages over 30: [35 58 41 67]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("element-wise multiply:\n", A * B)
print("\nmatrix multiply (dot product):\n", A @ B)

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("\ndot product of vectors:", v1 @ v2)

print("\ntranspose of A:\n", A.T)

element-wise multiply:
 [[ 5 12]
 [21 32]]

matrix multiply (dot product):
 [[19 22]
 [43 50]]

dot product of vectors: 32

transpose of A:
 [[1 3]
 [2 4]]
